package openvpn

// CredentialsProvider returns client's current auth primitives (i.e. customer identity signature / node's sessionId)
type CredentialsProvider func() (username string, password string, err error)

// SessionStats represents statistics, generated by bytescount middleware
type SessionStats struct {
	BytesSent, BytesReceived int
}

// SessionStatsHandler is invoked when middleware receives statistics
type SessionStatsHandler func(SessionStats) error

// Callback is called when openvpn process state changes
type Callback func(state State)
